<script type="text/javascript">
		var _spmq = <?php echo $this->getUserInfosJson();?>;
		(function() {
		var spm = document.createElement('script'); spm.type = 'text/javascript'; spm.async = true;
		spm.src = '<?php echo $this->getClientUrl();?>/remote/script.js?<?php echo $this->getUserInfosEncode();?>';
		var s_spm = document.getElementsByTagName('script')[0]; s_spm.parentNode.insertBefore(spm, s_spm);
		})();
</script>