language: php

php:
  - 5.3
  - 5.4
  - 5.5

sudo: false

env:
  - MAGENTO_VERSION=1.5.1.0
  - MAGENTO_VERSION=1.6.2.0
  - MAGENTO_VERSION=1.7.0.2
  - MAGENTO_VERSION=1.8.1.0
  - MAGENTO_VERSION=1.9.1.0

matrix:
  fast_finish: true

before_script:
  - phpenv config-add travis_tests_config.ini
  - MAGE_CI_SETUP_ONLY=1 composer test ${MAGENTO_VERSION}

script:
  - COMPOSER_PROCESS_TIMEOUT=3600 composer test ${MAGENTO_VERSION}

