language: php

php:
  - 5.3
  - 5.4
  - 5.5

sudo: required
services:
  - docker

env:
  - MAGENTO_VERSION=1.6.2.0-patch2
  - MAGENTO_VERSION=1.7.0.2-patch8
  - MAGENTO_VERSION=1.8.1.0-patch2
  - MAGENTO_VERSION=1.9.1.1-patch4
  - MAGENTO_VERSION=1.9.2.2-patch1

matrix:
  fast_finish: true

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - composer -n install
  - TRAVIS_PHP_VERSION=${TRAVIS_PHP_VERSION} docker-compose build
  - TRAVIS_PHP_VERSION=${TRAVIS_PHP_VERSION} docker-compose up -d
  - sleep 20
  - TRAVIS_PHP_VERSION=${TRAVIS_PHP_VERSION} bin/test.sh ${MAGENTO_VERSION}
