language: php

php:
  - '5.6'

sudo: required
services:
  - docker

env:
  - MAGENTO_VERSION=1.6.2.0
  - MAGENTO_VERSION=1.7.0.2
  - MAGENTO_VERSION=1.8.1.0
  - MAGENTO_VERSION=1.9.1.1
  - MAGENTO_VERSION=1.9.2.2

matrix:
  fast_finish: true

script:
  - composer -n install
  - docker-compose build
  - docker-compose up -d
  - docker-compose run --rm -e ENV_MAGE_VER=${MAGENTO_VERSION} test
