language: php

php:
  - 5.3
  - 5.4
  - 5.5

sudo: false

env:
  - MAGENTO_VERSION=magento-ce-1.5.1.0
  - MAGENTO_VERSION=magento-ce-1.5.1.0 USE_FLAT_CATALOG=1
  - MAGENTO_VERSION=magento-ce-1.6.2.0
  - MAGENTO_VERSION=magento-ce-1.6.2.0 USE_FLAT_CATALOG=1
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  - MAGENTO_VERSION=magento-ce-1.7.0.2 USE_FLAT_CATALOG=1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.8.1.0 USE_FLAT_CATALOG=1
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.2 USE_FLAT_CATALOG=1

matrix:
  fast_finish: true

script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
