db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: "root"

test:
  build: ./docker/magento-test
  volumes:
    - .:/src
    - ./magento_src:/magento_src
  ports:
    - 80
  links:
    - db
  environment:
    VIRTUAL_HOST: shopymind.test
