<br /><br /><div style="text-align:center;"><a href="http://www.shopymind.com/" target="_blank"><img src="http://media.shopymind.com/img/logo.png" /></a></div><br /><br /><ul class="messages"><li class="notice-msg"><?=$this->__('Afin d\'utiliser shopymind, vous devez créer un compte gratuitement');?> <a href="http://client.shopymind.com/registration/speed" target="_blank"><?=$this->__('en cliquant ici');?></a></li></ul>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('ShopyMind Configuration')?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span><?=$this->__('Send')?></span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">

    <form id="edit_form" name="edit_form" method="post" action="<?=$this->getUrl('*/*/post')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <input name="SPMForm[defaultLang]" type="hidden" value="<?php echo substr(Mage::app()->getLocale()->getDefaultLocale(),0,2) ?>" />
        <input name="SPMForm[defaultCurrency]" type="hidden" value="<?php echo Mage::app()->getStore()->getDefaultCurrencyCode() ?>" />
        <input name="SPMForm[contactPage]" type="hidden" value="<?php echo Mage::getUrl('contacts') ?>" />
        <input name="SPMForm[phoneNumber]" type="hidden" value="<?php echo Mage::getStoreConfig('general/store_information/phone') ?>" />
        <input name="SPMForm[timezone]" type="hidden" value="<?php echo Mage::getStoreConfig('general/locale/timezone') ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Login Information')?></h4>
        <fieldset id="spm_login">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('API key')?> <span class="required">*</span></td>
                    <td class="value"><input class="input-text required-entry" name="SPMForm[apiIdentification]" value="<?=htmlentities(Mage::getStoreConfig('shopymind/configuration/apiidentification'),ENT_COMPAT,'UTF-8');?>" /></td>
                </tr>
                <tr>
                    <td class="label"><?=$this->__('API password')?> <span class="required">*</span></td>
                    <td class="value"><input type="password" class="input-text required-entry" name="SPMForm[apiPassword]" value="<?=htmlentities(Mage::getStoreConfig('shopymind/configuration/apipassword'),ENT_COMPAT,'UTF-8');?>" /></td>
                </tr>
            </table>
        </fieldset>
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Configuration')?></h4>
        <fieldset id="spm_login">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Make the field date of birth required')?></td>
                    <td class="value"><select class="select required-entry" name="SPMForm[birthRequired]"><option value="no"<?=(Mage::getStoreConfig('shopymind/configuration/birthrequired') == 'no'? ' selected="selected"':'')?>><?=$this->__('No')?></option><option value="yes"<?=(!Mage::getStoreConfig('shopymind/configuration/birthrequired') || Mage::getStoreConfig('shopymind/configuration/birthrequired') == 'yes'? ' selected="selected"':'')?>><?=$this->__('Yes')?></option></select>
                    <p class="note"><span><strong style="color:red"><?=$this->__('Recommended')?></strong></span></p>
                    </td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>